<a href="https://colab.research.google.com/github/prnakyazze94/Data-602/blob/main/Discussion_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd


# -------------------------------------------------------------
# NumPy: Homogeneous, position-based numerical computations
# -------------------------------------------------------------
np_arr = np.array([10, 20, 30, 40])

# Vectorized operation
print("NumPy Vectorized Add:", np_arr + 5)
# Output: [15 25 35 45]

# Position-based indexing
print("NumPy Slicing:", np_arr[:2])
# Output: [10 20]


# -------------------------------------------------------------
# Pandas: Heterogeneous, labeled tabular data manipulation
# -------------------------------------------------------------
df = pd.DataFrame(
    {
        "Product": ["Apples", "Bananas", "Cherries"],
        "Price": [1.20, 0.50, 2.75],
        "In_Stock": [True, False, True],
    }
)

# Label-based selection and filtering
print(df[df["Price"] > 1.00])
# Output:
#     Product  Price  In_Stock
# 0    Apples   1.20      True
# 2  Cherries   2.75      True

# Grouping and aggregation (not natively available in NumPy)
print("Mean price:", df["Price"].mean())
# Output: Mean price: 1.4833333333333334

NumPy Vectorized Add: [15 25 35 45]
NumPy Slicing: [10 20]
    Product  Price  In_Stock
0    Apples   1.20      True
2  Cherries   2.75      True
Mean price: 1.4833333333333334


. Create a 1D array of numbers from 0 to 9

In [2]:


# Using np.arange to generate numbers from 0 up to (but not including) 10
arr = np.arange(10)

print(repr(arr))
# Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Extract all odd numbers from array1

In [3]:


array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Boolean indexing: select elements where the remainder divided by 2 is not 0
odd_numbers = array1[array1 % 2 != 0]

print(repr(odd_numbers))
# Output: array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])


. Get the common items between a and  b  

In [4]:


a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

common_items = np.intersect1d(a, b)

print(repr(common_items))
# Desired Output: array([2, 4])

array([2, 4])


From array a remove all items present in array  b

In [1]:


# Input:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Remove all items in 'a' that are present in 'b'
result = np.setdiff1d(a, b)

print(repr(result))
# Desired Output: array([1, 2, 3, 4])

array([1, 2, 3, 4])


 Find out if iris has any missing values.

In [3]:


# Input
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = np.genfromtxt(url, delimiter=",", dtype="float", usecols=[0, 1, 2, 3])

# Check if there are any NaN values
has_missing = np.isnan(iris).any()

print("Does iris have any missing values?", has_missing)
# Output: False

Does iris have any missing values? False
